/**
 * This file is auto generated by Twin Dragons Tools
 * JackpotPopupView.h
 * DragonVideoPoker
 *
 * Created by Dung Ta Van on Wed Jun 04 09:56:22 GMT+07:00 2014
 *
 **/

#ifndef __DragonVideoPoker__JackpotPopupView__
#define __DragonVideoPoker__JackpotPopupView__

#include "cocos-ext.h"

#include "PopUpLayer.h"
#include "Defines.h"

using namespace std;
using namespace cocos2d;

class JackpotPopupView : public PopUpLayer {
    
public:
	static JackpotPopupView* create(string jackpotString,
                                    long long jackpotValue,
                                    string pBackgroundImage = D::id.jackpot_popup_background_container,
                                    string pExitNormalImage = "",
                                    string pExitSelectedImage = "");
    
    virtual bool init(string jackpotString,
                      long long jackpotValue,
                      string pBackgroundImage = "pop_common_bg.png",
                      string pExitNormalImage = "",
                      string pExitSelectedImage = "");
    
protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    virtual void onActionShowFinished();

private:
	enum MenuItemTag {
		okMenuItemTag = 1000,
        shareMenuItemTag = 1001
	};
	
    void addStarSprites();
	void jackpotMenuItemCallback(CCObject *pSender);
	
	//{extend_functions}
    
	CCMenuItem* mOkMenuItem;
	CCMenuItem* mShareMenuItem;
	
	CCSprite* mChipsSprite;
	CCSprite* mJackpotTextSprite;
	CCSprite* mRewardIconSprite;
	CCSprite* mShineCircleSprite;
	CCSprite* mStarShineSprite;
    
    CCLabelTTF *mChipsLabel;
    
    string mJackpotString;
    long long mJackpotValue;
};

#endif /* defined(__DragonVideoPoker__JackpotPopupView__) */

