/**
 * This file is auto generated by Twin Dragons Tools
 * AvatarsPopupView.h
 * DragonVideoPoker
 *
 * Created by Ta Van Dung on Thu May 29 15:55:14 GMT+07:00 2014
 *
 **/

#ifndef __DragonVideoPoker__AvatarsPopupView__
#define __DragonVideoPoker__AvatarsPopupView__

#include "cocos-ext.h"

#include "PopUpLayer.h"

using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class AvatarsPopupView : public PopUpLayer {
    
public:
	static AvatarsPopupView* create(string pBackgroundImage = "pop_common_bg.png",
                                    string pExitNormalImage = "pop_common_close_normal.png",
                                    string pExitSelectedImage = "pop_common_close_active.png");
    
    virtual bool init(string pBackgroundImage = "pop_common_bg.png",
                      string pExitNormalImage = "pop_common_close_normal.png",
                      string pExitSelectedImage = "pop_common_close_active.png");
    
protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void onExit();
    
private:
	enum MenuItemTag {
		
	};
	
	void avatarsMenuItemCallback(CCObject *pSender);
    void addAvatarsSprites();
    void addContainerTable();
	
	//{extend_functions}
	
	CCSprite* mComeBackTextSprite;
	CCSprite* mHeaderSprite;
	
	CCSprite* mCurrentBackgroundSprite;
	CCSprite* mFacebookIconSprite;
	CCSprite* mInframeSprite;
	CCSprite* mUseBackgroundSprite;
    CCSprite* mSelectedSprite;
    
	vector<CCSprite*> mAvatarsSprites;
    
	CCMenuItem* mUseMenuitemMenuItem;
    
	CCMenu* mUseMenu;
    
	CCTableView* mContainerTable;
    
    long mSelectedAvatarIndex;
    
};

#endif /* defined(__DragonVideoPoker__AvatarsPopupView__) */

