/**
* This file is auto generated by Twin Dragons Tools
* CrazyShoppingPopupCellView.cpp
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#ifndef __ComplexExample__CrazyShoppingPopupCellView__
#define __ComplexExample__CrazyShoppingPopupCellView__
#include "cocos-ext.h"
#include "ITableCellView.h"
#include "Defines.h"
using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class CrazyShoppingPopupCellView : public ITableCellView {
public:
	static CrazyShoppingPopupCellView* create(//{parameters},
							const int &idx);
	virtual bool init(//{parameters},
					const int &idx = 0);
	virtual void update(const int &idx);
protected:
	virtual void addSprites();
    virtual void addLabels();
    virtual void addMenus();
    virtual void addMenuItems();
    
    virtual void updateSprites(const int &idx);
    virtual void updateLabels(const int &idx);
    virtual void updateMenuItems(const int &idx);
private:
	enum ElementTag {
		
		shoppingBgmenuTag = 1,

		packagemenuitemTag = 1,
		packagemenuitemTag1 = 2,

	};
	void crazyShoppingPopupMenuItemCallback(CCObject *pSender);
	
	CCMenuItem* mPackageMenuItems[2];

	CCMenu* mShoppingBgMenu;

	//{extend_functions_declaring}
};
#endif /* defined(__ComplexExample__CrazyShoppingPopupCellView__) */
