/**
* This file is auto generated by Twin Dragons Tools
* CrazyShoppingPopupView.h
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#ifndef __ComplexExample__CrazyShoppingPopupView__
#define __ComplexExample__CrazyShoppingPopupView__
#include "cocos-ext.h"
#include "PopUpLayer.h"
#include "ITableViewBuilder.h"
#include "Defines.h"
using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;
class ITableCellView;
class TableView;
class CrazyShoppingPopupView : public PopUpLayer, public ITableViewBuilder {
public:
	static CrazyShoppingPopupView* create(//{parameters},
							string pBackgroundImage = D::id.pop_common_bg,
                            string pExitNormalImage = D::id.pop_common_close_normal,
                            string pExitSelectedImage = D::id.pop_common_close_active);
    
    virtual bool init(//{parameters}
    				string pBackgroundImage = D::id.pop_common_bg,
                    string pExitNormalImage = D::id.pop_common_close_normal,
                    string pExitSelectedImage = D::id.pop_common_close_active);	
                    
   	virtual ITableCellView* createTableViewCellAt(const int &idx);
 
 protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenus();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    virtual void addTables();
    
private:
	enum MenuItemTag {
		
	};
	
	void crazyShoppingMenuItemCallback(CCObject *pSender);
	
	CCSprite* mCzsHeaderSprite;

	CCTableView* mShoppingTable;

};
#endif /* defined(__ComplexExample__CrazyShoppingPopupView__) */
