/**
* This file is auto generated by Twin Dragons Tools
* CrazyShoppingPopupCellView.cpp
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#include "CrazyShoppingPopupCellView.h"
#include "ITableCellView.h"
#include "TableView.h"
#include "VisibleRect.h"
#include "GameParams.h"
#include "PackageMenuItemView.h"

//{extend_class}

CrazyShoppingPopupCellView* CrazyShoppingPopupCellView::create(//{parameters},
										const int &idx) {
    CrazyShoppingPopupCellView* pRet = new CrazyShoppingPopupCellView();
    pRet->autorelease();
    pRet->init(//{importing_params},
    		idx);
    
    return pRet;
}

bool CrazyShoppingPopupCellView::init(//{parameters},
							const int &idx) {             
	
    return ITableCellView::init(idx);
}

void CrazyShoppingPopupCellView::addMenus() {
	ITableCellView::addMenus();
    
    	//create group of menus
	mShoppingBgMenu = CCMenu::create();
	mShoppingBgMenu->setAnchorPoint(CCPoint(0, 0));
	mShoppingBgMenu->setPosition(CCPoint(0, 0));
	this->addChild(mShoppingBgMenu);

}

void CrazyShoppingPopupCellView::addMenuItems() {
    ITableCellView::addMenuItems();
    
    	//create group of menuitems
	for(int i = 0 ; i < 2 ; i++) {
		mPackageMenuItems[i] = PackageMenuItemView::create(0,
							"dung",
							this,
							menu_selector(CrazyShoppingPopupCellView::crazyShoppingPopupMenuItemCallback));
		mPackageMenuItems[i]->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_PACKAGE_MENUITEM_POSITIONS[i]);
		mShoppingBgMenu->addChild(mPackageMenuItems[i], 0, packagemenuitemTag);
	}

}

void CrazyShoppingPopupCellView::addSprites() {
	ITableCellView::addSprites();
   
}

void CrazyShoppingPopupCellView::addLabels() {
	ITableCellView::addLabels();	
   
}

void CrazyShoppingPopupCellView::updateSprites(const int &idx) {
	ITableCellView::updateSprites(idx);
	
	//{update_sprites}
}

void CrazyShoppingPopupCellView::updateLabels(const int &idx) {
	ITableCellView::updateLabels(idx);
	
	//{update_labels}
}

void CrazyShoppingPopupCellView::updateMenuItems(const int &idx) {
	ITableCellView::updateMenuItems(idx);
	
	//{update_menuitems}
}

void CrazyShoppingPopupCellView::update(const int &idx) {
	ITableCellView::update(idx);
	
	//{update_cell_view}
}

//{extend_functions_implementing}

void CrazyShoppingPopupCellView::crazyShoppingPopupMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
