/**
* This file is auto generated by Twin Dragons Tools
* CrazyShoppingPopupView.cpp
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#include "CrazyShoppingPopupView.h"
#include "PopUpLayer.h"
#include "ITableCellView.h"
#include "TableView.h"
#include "VisibleRect.h"
#include "GameParams.h"
#include "CzsHeaderspriteView.h"

#include "CrazyShoppingPopupCellView.h"

#include "PackageMenuItemView.h"



CrazyShoppingPopupView* CrazyShoppingPopupView::create(//{parameters},
							string pBackgroundImage,
							string pExitNormalImage,
							string pExitSelectedImage) {
    CrazyShoppingPopupView* pRet = new CrazyShoppingPopupView();
    pRet->autorelease();
    pRet->init(//{importing_params}
    		pBackgroundImage, 
    		pExitNormalImage, 
    		pExitSelectedImage);
    
    return pRet;
}

bool CrazyShoppingPopupView::init(//{parameters},
							string pBackgroundImage,
							string pExitNormalImage,
                            string pExitSelectedImage) {             
	
    PopUpLayer::init(pBackgroundImage,
                     pExitNormalImage,
                     pExitSelectedImage,
                     GPARAMS().POPUP_CRAZY_SHOPPING_POP_COMMON_CLOSE_NORMAL_SPRITE_POSITION);
    setBackgroundPosition(VisibleRect::center());
    
    return true;
}

void CrazyShoppingPopupView::addMenus() {
	PopUpLayer::addMenus();
    
}

void CrazyShoppingPopupView::addMenuItems() {
    PopUpLayer::addMenuItems();
    
}

void CrazyShoppingPopupView::addSprites() {
	PopUpLayer::addSprites();
   
   		//create group of sprites
	mCzsHeaderSprite = CzsHeaderspriteView::create(D::id.crazy_shopping_popup_czs_header.c_str());
	mCzsHeaderSprite->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CZS_HEADER_SPRITE_POSITION);
	mBackgroundSprite->addChild(mCzsHeaderSprite, 0);

}

void CrazyShoppingPopupView::addLabels() {
	PopUpLayer::addLabels();	
   
}

void CrazyShoppingPopupView::addProgressBars() {
	PopUpLayer::addProgressBars();
	
}

void CrazyShoppingPopupView::addTables() {
	PopUpLayer::addTables();
	
		//create group of tables
	mShoppingTable = TableView::create(
					GPARAMS().POPUP_CRAZY_SHOPPING_SHOPPING_TABLE_SIZE,
					3,
					1,
					GPARAMS().POPUP_CRAZY_SHOPPING_SHOPPING_CELL_POSITION,
					GPARAMS().POPUP_CRAZY_SHOPPING_SHOPPING_CELL_SIZE,
					this);
	mShoppingTable->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_SHOPPING_TABLE_POSITION);
	mShoppingTable->setTouchPriority(kCCMenuHandlerPriority - 101);
	mBackgroundSprite->addChild(mShoppingTable);

}

void CrazyShoppingPopupView::addActions() {
    PopUpLayer::addActions();
    
    //{add_actions}
}

ITableCellView* CrazyShoppingPopupView::createTableViewCellAt(const int &idx) {
    ITableCellView *pRet = CrazyShoppingPopupCellView::create(idx);
    
    return pRet;
}

void CrazyShoppingPopupView::crazyShoppingMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
