/**
* This file is auto generated by TVD Tools
* CzsHeaderspriteView.cpp
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#include "CzsHeaderspriteView.h"
#include "GameParams.h"

CzsHeaderspriteView* CzsHeaderspriteView::create(const char* pmBgName
									) {
    CzsHeaderspriteView* pRet = new CzsHeaderspriteView();
    pRet->autorelease();
    pRet->init(pmBgName
    			);
    
    return pRet;
}

bool CzsHeaderspriteView::init(const char* pmBgName
						) {             
	
	this->mmBgName = pmBgName;

	this->addSprites();
	this->addMenus();
	this->addMenuItems();
	this->addLabels();
    return CCSprite::initWithFile(D::id.crazy_shopping_popup_czs_header.c_str());
}

void CzsHeaderspriteView::addMenus() {
    
}

void CzsHeaderspriteView::addMenuItems() {
    
}

void CzsHeaderspriteView::addSprites() {
   	
}

void CzsHeaderspriteView::addLabels() {
   
}

//{extend_functions_implementing}

void CzsHeaderspriteView::czsHeaderMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
//====================== end ======================
