/**
* This file is auto generated by Twin Dragons Tools
* PackageMenuItemView.h
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#ifndef __ComplexExample__PackageMenuItemView__
#define __ComplexExample__PackageMenuItemView__
#include "cocos-ext.h"
#include "cocos2d.h"
#include "Defines.h"
using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class PackageMenuItemView : public CCMenuItemSprite {
public:
	static PackageMenuItemView* create(int pIndex, 
							char* pCharacter,
							CCObject *target,
							SEL_MenuHandler selector);
	virtual bool init(int pIndex, 
							char* pCharacter,
					CCObject *target,
					SEL_MenuHandler selector);
protected:
	virtual void addSprites();
    virtual void addLabels();
    virtual void addMenus();
    virtual void addMenuItems();
private:
	enum ElementTag {
		
		titlelabelTag = 1,
		chipslabelTag = 2,

		moneylabelTag = 5,

		buyActivemenuTag = 1,

		buymenuTag = 5,

		childActivemenuitemTag = 1,

		childmenuitemTag = 5,

		czsChipIconActivespriteTag = 1,
		czsMainIconActivespriteTag = 2,

		czsBuyActive1spriteTag = 8,
		czsBuyNormal1spriteTag = 9,

		czsChipIconspriteTag = 9,
		czsMainIcon1spriteTag = 10,

		czsBuyActivespriteTag = 10,
		czsBuyNormalspriteTag = 11,

		blueActivespriteTag = 11,
		blueNormalspriteTag = 12,

	};
	void packageMenuItemCallback(CCObject *pSender);
	
	CCLabelTTF* mTitleLabel;
	CCLabelTTF* mChipsLabel;

	CCLabelTTF* mMoneyLabel;

	CCSprite* mCzsChipIconActiveSprite;
	CCSprite* mCzsMainIconActiveSprite;

	CCSprite* mCzsBuyActive1Sprite;
	CCSprite* mCzsBuyNormal1Sprite;

	CCSprite* mCzsChipIconSprite;
	CCSprite* mCzsMainIcon1Sprite;

	CCSprite* mCzsBuyActiveSprite;
	CCSprite* mCzsBuyNormalSprite;

	CCSprite* mBlueActiveSprite;
	CCSprite* mBlueNormalSprite;

	CCMenuItem* mChildActiveMenuItem;

	CCMenuItem* mChildMenuItem;

	CCMenu* mBuyActiveMenu;

	CCMenu* mBuyMenu;

	int mIndex;
	char* mCharacter;

	//{extend_functions_declaring}
};

#endif /* defined(__ComplexExample__PackageMenuItemView__) */
