/**
* This file is auto generated by TVD Tools
* PackageMenuItemView.cpp
* ComplexExample
*
* Created by apple on Wed Sep 17 15:31:07 GMT+07:00 2014
*
**/
#include "PackageMenuItemView.h"
#include "GameParams.h"

PackageMenuItemView* PackageMenuItemView::create(int pIndex, 
							char* pCharacter,
									CCObject *target,
									SEL_MenuHandler selector) {
    PackageMenuItemView* pRet = new PackageMenuItemView();
    pRet->autorelease();
    pRet->init(pIndex, 
			pCharacter,
    		target,
    		selector);
    
    return pRet;
}

bool PackageMenuItemView::init(int pIndex, 
							char* pCharacter,
						CCObject *target,
						SEL_MenuHandler selector) {             
	
	this->mIndex = pIndex;
	this->mCharacter = pCharacter;

	this->addSprites();
	this->addMenus();
	this->addMenuItems();
	this->addLabels();
    return CCMenuItemSprite::initWithNormalSprite(
    							mBlueNormalSprite,
    							mBlueActiveSprite,
    							NULL,
    							target,
    							selector);
}

void PackageMenuItemView::addMenus() {
    	//create group of menus
	mBuyMenu = CCMenu::create();
	mBuyMenu->setAnchorPoint(CCPoint(0, 0));
	mBuyMenu->setPosition(CCPoint(0, 0));
	mBlueNormalSprite->addChild(mBuyMenu);

	//create group of menus
	mBuyActiveMenu = CCMenu::create();
	mBuyActiveMenu->setAnchorPoint(CCPoint(0, 0));
	mBuyActiveMenu->setPosition(CCPoint(0, 0));
	mBlueActiveSprite->addChild(mBuyActiveMenu);

}

void PackageMenuItemView::addMenuItems() {
    	//create group of menuitems
	//create group of sprites
	mCzsBuyActiveSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_normal_buy_child_czs_buy_active.c_str());

	mCzsBuyNormalSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_normal_buy_child_czs_buy_normal.c_str());

	//create group of labels
	mMoneyLabel = CCLabelTTF::create("$99",
			"HelveticaNeue",
			12.0);
	mMoneyLabel->setColor(ccc3(255, 255, 255));
	mMoneyLabel->setAnchorPoint(CCPoint(0.5, 0.5));
	mMoneyLabel->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_MONEY_LABEL_POSITION);
	mCzsBuyNormalSprite->addChild(mMoneyLabel, 0);

	mChildMenuItem = CCMenuItemSprite::create(mCzsBuyNormalSprite,
						mCzsBuyActiveSprite,
						this,
						menu_selector(PackageMenuItemView::packageMenuItemCallback));
	mChildMenuItem->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CHILD_MENUITEM_POSITION);
	mBuyMenu->addChild(mChildMenuItem, 0, childmenuitemTag);

	//create group of menuitems
	//create group of sprites
	mCzsBuyActive1Sprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_active_buy_child_czs_buy_active.c_str());

	mCzsBuyNormal1Sprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_active_buy_child_czs_buy_normal.c_str());

	mChildActiveMenuItem = CCMenuItemSprite::create(mCzsBuyNormal1Sprite,
						mCzsBuyActive1Sprite,
						this,
						menu_selector(PackageMenuItemView::packageMenuItemCallback));
	mChildActiveMenuItem->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CHILD_ACTIVE_MENUITEM_POSITION);
	mBuyActiveMenu->addChild(mChildActiveMenuItem, 0, childActivemenuitemTag);

}

void PackageMenuItemView::addSprites() {
   		//create group of sprites
	mBlueActiveSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_active_czs_bg_blue_active.c_str());

	mBlueNormalSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_normal_czs_bg_blue_normal.c_str());

	//create group of sprites
	mCzsChipIconSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_normal_czs_chip_icon.c_str());
	mCzsChipIconSprite->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CZS_CHIP_ICON_SPRITE_POSITION);
	mBlueNormalSprite->addChild(mCzsChipIconSprite, 0);

	mCzsMainIcon1Sprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_normal_czs_main_icon_1.c_str());
	mCzsMainIcon1Sprite->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CZS_MAIN_ICON_1_SPRITE_POSITION);
	mBlueNormalSprite->addChild(mCzsMainIcon1Sprite, 0);

	//create group of sprites
	mCzsChipIconActiveSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_active_czs_chip_icon.c_str());
	mCzsChipIconActiveSprite->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CZS_CHIP_ICON_ACTIVE_SPRITE_POSITION);
	mBlueActiveSprite->addChild(mCzsChipIconActiveSprite, 0);

	mCzsMainIconActiveSprite = 
		CCSprite::create(D::id.crazy_shopping_popup_shopping_cell_shopping_bg_package_blue_active_czs_main_icon_1.c_str());
	mCzsMainIconActiveSprite->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CZS_MAIN_ICON_ACTIVE_SPRITE_POSITION);
	mBlueActiveSprite->addChild(mCzsMainIconActiveSprite, 0);

}

void PackageMenuItemView::addLabels() {
   
	//create group of labels
	mTitleLabel = CCLabelTTF::create("Pound of chips",
			"HelveticaNeue",
			16.0);
	mTitleLabel->setColor(ccc3(255, 255, 255));
	mTitleLabel->setAnchorPoint(CCPoint(0.5, 0.5));
	mTitleLabel->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_TITLE_LABEL_POSITION);
	mBlueNormalSprite->addChild(mTitleLabel, 0);

	mChipsLabel = CCLabelTTF::create("1.000.000",
			"HelveticaNeue",
			11.0);
	mChipsLabel->setColor(ccc3(255, 0, 0));
	mChipsLabel->setAnchorPoint(CCPoint(0.5, 0.5));
	mChipsLabel->setPosition(GPARAMS().POPUP_CRAZY_SHOPPING_CHIPS_LABEL_POSITION);
	mBlueNormalSprite->addChild(mChipsLabel, 0);

}

//{extend_functions_implementing}

void PackageMenuItemView::packageMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
//====================== end ======================
