/**
* This file is auto generated by Twin Dragons Tools
* LeaderboardPopupView.h
* DragonVideoPoker
*
* Created by apple on Wed Aug 13 11:45:33 GMT+07:00 2014
*
**/

#ifndef __DragonVideoPoker__LeaderboardPopupView__
#define __DragonVideoPoker__LeaderboardPopupView__

#include "cocos-ext.h"

#include "PopUpLayer.h"
#include "Defines.h"

using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class LeaderboardPopupView : public PopUpLayer {

public:
	static LeaderboardPopupView* create(
							string pBackgroundImage = D::id.common_background,
                            string pExitNormalImage = "",
                            string pExitSelectedImage = "");
    
    virtual bool init(
    				string pBackgroundImage = D::id.common_background,
                    string pExitNormalImage = "",
                    string pExitSelectedImage = "");	
 
 protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    
private:
	enum MenuItemTag {
		
	};
	
	void leaderboardMenuItemCallback(CCObject *pSender);
	
	CCSprite* mBgSprite;
	
	CCSprite* mBgNumberSprite;
	
	CCSprite* mLeaderboardBannerSprite;
	
	CCSprite* mNumber1Sprite;
	
	CCSprite* mNumber2Sprite;
	
	CCSprite* mNumber3Sprite;

};

#endif /* defined(__DragonVideoPoker__LeaderboardPopupView__) */
