/**
* This file is auto generated by Twin Dragons Tools
* LeaderboardPopupView.cpp
* DragonVideoPoker
*
* Created by apple on Wed Aug 13 11:45:46 GMT+07:00 2014
*
**/
#include "LeaderboardPopupView.h"
#include "PopUpLayer.h"
#include "VisibleRect.h"
#include "GameParams.h"

LeaderboardPopupView* LeaderboardPopupView::create(,
							string pBackgroundImage,
							string pExitNormalImage,
							string pExitSelectedImage) {
    LeaderboardPopupView* pRet = new LeaderboardPopupView();
    pRet->autorelease();
    pRet->init(
    		pBackgroundImage, 
    		pExitNormalImage, 
    		pExitSelectedImage);
    
    return pRet;
}

bool LeaderboardPopupView::init(
							string pBackgroundImage,
							string pExitNormalImage,
                            string pExitSelectedImage) {             
	
    PopUpLayer::init(pBackgroundImage,
                     pExitNormalImage,
                     pExitSelectedImage,
                     GPARAMS().POP_COMMON_EXIT_BUTTON_POSITION);
    setBackgroundPosition(VisibleRect::center());
    
    return true;
}

void LeaderboardPopupView::addMenuItems() {
    PopUpLayer::addMenuItems();
    
}

void LeaderboardPopupView::addSprites() {
	PopUpLayer::addSprites();
   
	//create group of elements
	mBgSprite = 
		CCSprite::create(D::id.leaderboard_popup_bg.c_str());
	mBgSprite->setPosition(GPARAMS().POP_LEADERBOARD_BG_SPRITE_POSITION);
	mBackgroundSprite->addChild(mBgSprite, 0);

	mBgNumberSprite = 
		CCSprite::create(D::id.leaderboard_popup_bg_number.c_str());
	mBgNumberSprite->setPosition(GPARAMS().POP_LEADERBOARD_BG_NUMBER_SPRITE_POSITION);
	mBackgroundSprite->addChild(mBgNumberSprite, 0);

	mLeaderboardBannerSprite = 
		CCSprite::create(D::id.leaderboard_popup_leaderboard_banner.c_str());
	mLeaderboardBannerSprite->setPosition(GPARAMS().POP_LEADERBOARD_LEADERBOARD_BANNER_SPRITE_POSITION);
	mBackgroundSprite->addChild(mLeaderboardBannerSprite, 0);

	mNumber1Sprite = 
		CCSprite::create(D::id.leaderboard_popup_number_1.c_str());
	mNumber1Sprite->setPosition(GPARAMS().POP_LEADERBOARD_NUMBER_1_SPRITE_POSITION);
	mBackgroundSprite->addChild(mNumber1Sprite, 0);

	mNumber2Sprite = 
		CCSprite::create(D::id.leaderboard_popup_number_2.c_str());
	mNumber2Sprite->setPosition(GPARAMS().POP_LEADERBOARD_NUMBER_2_SPRITE_POSITION);
	mBackgroundSprite->addChild(mNumber2Sprite, 0);

	mNumber3Sprite = 
		CCSprite::create(D::id.leaderboard_popup_number_3.c_str());
	mNumber3Sprite->setPosition(GPARAMS().POP_LEADERBOARD_NUMBER_3_SPRITE_POSITION);
	mBackgroundSprite->addChild(mNumber3Sprite, 0);

}

void LeaderboardPopupView::addLabels() {
	PopUpLayer::addLabels();	
   
}

void LeaderboardPopupView::addProgressBars() {
	PopUpLayer::addProgressBars();
	
	//{add_progressbars}
}

void LeaderboardPopupView::addTables() {
	PopUpLayer::addTables();
	
}

void LeaderboardPopupView::addActions() {
    PopUpLayer::addActions();
    
    //{add_actions}
}

void LeaderboardPopupView::leaderboardMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
