/**
* This file is auto generated by Twin Dragons Tools
* CrazyUpgradePopupView.cpp
* DragonVideoPoker
*
* Created by apple on Fri Aug 15 20:12:12 GMT+07:00 2014
*
**/
#include "CrazyUpgradePopupView.h"
#include "PopUpLayer.h"
#include "VisibleRect.h"
#include "GameParams.h"

CrazyUpgradePopupView* CrazyUpgradePopupView::create(
							string pBackgroundImage,
							string pExitNormalImage,
							string pExitSelectedImage) {
    CrazyUpgradePopupView* pRet = new CrazyUpgradePopupView();
    pRet->autorelease();
    pRet->init(
    		pBackgroundImage, 
    		pExitNormalImage, 
    		pExitSelectedImage);
    
    return pRet;
}

bool CrazyUpgradePopupView::init(//{parameters}
							string pBackgroundImage,
							string pExitNormalImage,
                            string pExitSelectedImage) {             
	
    PopUpLayer::init(pBackgroundImage,
                     pExitNormalImage,
                     pExitSelectedImage,
                     GPARAMS().POP_COMMON_EXIT_BUTTON_POSITION);
    setBackgroundPosition(VisibleRect::center());
    
    return true;
}

void CrazyUpgradePopupView::addMenuItems() {
    PopUpLayer::addMenuItems();
    
}

void CrazyUpgradePopupView::addSprites() {
	PopUpLayer::addSprites();
   
   		//create group of elements
	mCzRewardIconSprite = 
		CCSprite::create(D::id.crazy_upgrade_popup_cz_reward_icon.c_str());
	mCzRewardIconSprite->setPosition(GPARAMS().POP_CRAZY_UPGRADE_CZ_REWARD_ICON_SPRITE_POSITION);
	mBackgroundSprite->addChild(mCzRewardIconSprite, 0);

	mCzVipLevelRibbonSprite = 
		CCSprite::create(D::id.crazy_upgrade_popup_cz_vip_level_ribbon.c_str());
	mCzVipLevelRibbonSprite->setPosition(GPARAMS().POP_CRAZY_UPGRADE_CZ_VIP_LEVEL_RIBBON_SPRITE_POSITION);
	mBackgroundSprite->addChild(mCzVipLevelRibbonSprite, 0);

	//sprites for ribbon
	mHahaHahaSprite = 
		CCSprite::create(D::id.crazy_on_ribbon.c_str());
	mHahaHahaSprite->setPosition(GPARAMS().POP_CRAZY_UPGRADE_HAHA_HAHA_SPRITE_POSITION);
	mCzVipLevelRibbonSprite->addChild(mHahaHahaSprite, 0);

}

void CrazyUpgradePopupView::addLabels() {
	PopUpLayer::addLabels();	
   	//example labels
	mDungTaVanLabel = CCLabelTTF::create("Hello I'm Dung Ta Van",
			DEFAULT_FONT_NAME,
			GPARAMS().CMM_FONT_SIZE_3);
	mDungTaVanLabel->setAnchorPoint(CCPoint(0, 0.5));
	mDungTaVanLabel->setPosition(GPARAMS().POP_CRAZY_UPGRADE_DUNG_TA_VAN_LABEL_POSITION);
	mBackgroundSprite->addChild(mDungTaVanLabel, 100);

	//example labels
	mHelloMyLoveLabel = CCLabelTTF::create("Hello my love",
			DEFAULT_FONT_NAME,
			GPARAMS().CMM_FONT_SIZE_3);
	mHelloMyLoveLabel->setAnchorPoint(CCPoint(0, 0.5));
	mHelloMyLoveLabel->setPosition(GPARAMS().POP_CRAZY_UPGRADE_HELLO_MY_LOVE_LABEL_POSITION);
	mCzVipLevelRibbonSprite->addChild(mHelloMyLoveLabel, 100);

}

void CrazyUpgradePopupView::addProgressBars() {
	PopUpLayer::addProgressBars();
	
	//{add_progressbars}
}

void CrazyUpgradePopupView::addTables() {
	PopUpLayer::addTables();
	
}

void CrazyUpgradePopupView::addActions() {
    PopUpLayer::addActions();
    
    //{add_actions}
}

void CrazyUpgradePopupView::crazyUpgradeMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
