/**
* This file is auto generated by TVD Tools
* UseMenuItemView.cpp
* DragonVideoPoker
*
* Created by apple on Mon Sep 22 23:42:59 GMT+07:00 2014
*
**/
#include "UseMenuItemView.h"
#include "GameParams.h"

UseMenuItemView* UseMenuItemView::create(const int& pIndex, 
							const string& pString,
									CCObject *target,
									SEL_MenuHandler selector) {
    UseMenuItemView* pRet = new UseMenuItemView();
    pRet->autorelease();
    pRet->init(pIndex, 
			pString,
    		target,
    		selector);
    
    return pRet;
}

bool UseMenuItemView::init(const int& pIndex, 
							const string& pString,
						CCObject *target,
						SEL_MenuHandler selector) {             
	
	mIndex = pIndex;
	mString = pString;

	this->addSprites();
	this->addMenus();
	this->addMenuItems();
	this->addLabels();
    return CCMenuItemSprite::initWithNormalSprite(
    							mUseNormalSprite,
    							mUseActiveSprite,
    							NULL,
    							target,
    							selector);
}

void UseMenuItemView::addMenus() {
    
}

void UseMenuItemView::addMenuItems() {
    
}

void UseMenuItemView::addSprites() {
   		//create group of sprites
	mUseActiveSprite = 
		CCSprite::create(D::id.cza_avatars_popup_container_cell_cza_current_background_use_use_use_active.c_str());

	mUseNormalSprite = 
		CCSprite::create(D::id.cza_avatars_popup_container_cell_cza_current_background_use_use_use_normal.c_str());

}

void UseMenuItemView::addLabels() {
   	//create group of labels
	mDungLabel = CCLabelTTF::create("Dung",
			"HelveticaNeue",
			11.0);
	mDungLabel->setColor(ccc3(255, 0, 0));		
	mDungLabel->setAnchorPoint(CCPoint(0.5, 0.5));
	mDungLabel->setPosition(GPARAMS().POPUP_CZA_AVATARS_DUNG_LABEL_POSITION);
	mUseActiveSprite->addChild(mDungLabel, 0);

}

//{extend_functions_implementing}

void UseMenuItemView::useMenuItemCallback(CCObject *pSender) {
    
    CCMenuItem* menuItem = static_cast<CCMenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
//====================== end ======================
