/**
* This file is auto generated by Twin Dragons Tools
* LobbyLayerCellView.cpp
* TomCuaCaOnline
*
* Created by apple on Thu Sep 25 14:11:51 GMT+07:00 2014
*
**/
#include "LobbyLayerCellView.h"
#include "ITableCellView.h"
#include "TableView.h"

//{extend_class}

LobbyLayerCellView* LobbyLayerCellView::create(//{parameters},
										const int &idx) {
    LobbyLayerCellView* pRet = new LobbyLayerCellView();
    pRet->autorelease();
    pRet->init(//{importing_params},
    		idx);
    
    return pRet;
}

bool LobbyLayerCellView::init(//{parameters},
							const int &idx) {             
	
    return ITableCellView::init(idx);
}

void LobbyLayerCellView::addMenus() {
	ITableCellView::addMenus();
    
}

void LobbyLayerCellView::addMenuItems() {
    ITableCellView::addMenuItems();
    
}

void LobbyLayerCellView::addSprites() {
	ITableCellView::addSprites();

}

void LobbyLayerCellView::addLabels() {
	ITableCellView::addLabels();	
   	//create group of labels
    
    string text = string("Police have said\n they plan to dismantle\n the camp of colorful\n tents and art") +  "installations\n Thursday morning,\n urging protesters\n to leave peacefully.";
    
    Label *textLabel = Label::createWithSystemFont(text,
                                                   "Arial",
                                                   17);
    textLabel->setPosition(getContentSize()/2);
    this->addChild(textLabel);
}

void LobbyLayerCellView::update(const int &idx) {
	ITableCellView::update(idx);
	
	//{update_cell_view}
}

//{extend_functions_implementing}

void LobbyLayerCellView::lobbylayerMenuItemCallback(Ref *pSender) {
    
    MenuItem* menuItem = static_cast<MenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
void LobbyLayerCellView::processWhenHighlight() {
   
}
void LobbyLayerCellView::processWhenUnhighlight() {
   
}
void LobbyLayerCellView::processWhenTouched() {

}
void LobbyLayerCellView::processWhenWillRecycle() {
    CCLOG("hehe i will be recycled");
}
