/**
* This file is auto generated by Twin Dragons Tools
* LobbyLayerCellView.cpp
* TomCuaCaOnline
*
* Created by apple on Thu Sep 25 14:11:51 GMT+07:00 2014
*
**/
#ifndef __TomCuaCaOnline__LobbyLayerCellView__
#define __TomCuaCaOnline__LobbyLayerCellView__

#include "cocos-ext.h"

#include "ITableCellView.h"

using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class LobbyLayerCellView : public ITableCellView {
public:
	static LobbyLayerCellView* create(//{parameters},
							const int &idx);
	virtual bool init(//{parameters},
					const int &idx = 0);
	virtual void update(const int &idx);
	
	virtual void processWhenTouched();
    virtual void processWhenHighlight();
    virtual void processWhenUnhighlight();
    virtual void processWhenWillRecycle();
protected:
	virtual void addSprites();
    virtual void addLabels();
    virtual void addMenus();
    virtual void addMenuItems();
    
private:
	enum ElementTag {

	};
	void lobbylayerMenuItemCallback(Ref *pSender);

	//{extend_functions_declaring}
};
#endif /* defined(__TomCuaCaOnline__LobbyLayerCellView__) */
