//
//  GameParams.h
//  Dragon Poker
//
//  Created by Nguyen Tien Thanh on 9/10/13.
//
//

#ifndef __Dragon_Poker__GameParams__
#define __Dragon_Poker__GameParams__

#include "cocos2d.h"
#include "SingLeton.h"
#include "TdgServerDefine.h"


using namespace std;
USING_NS_CC;

// encode & decode game param on memory
//#define encodeParam(__X__) (__X__ * 5807 + 43201)
//#define decodeParam(__X__) (((__X__ - 43201) % 5807) == 0 ? ((__X__ - 43201) / 5807) : 0)

//#define encodeParam(__X__) (__X__)
//#define decodeParam(__X__) (__X__)

// Appirater

// Chartboost
#define CHARTBOOST_APP_ID               @"539e9fafc26ee42f77146f97"
#define CHARTBOOST_APP_SIGNATURE        @"4ec529c204bc974e232a2dab53c7600b1f1a00e1"
#define CHARTBOOST_GOT_HOURLY_BONUS     @"GOT HOURLY BONUS"

// language
#define LANGUAGE                        0   // 0 - En; 1 - Vi

#ifdef CC_TARGET_OS_IPHONE
#define DEFAULT_FONT_NAME                   "HelveticaRoundedLT-BoldCond"
#define PRODUCT_ID                          "883096461"

#else
#define DEFAULT_FONT_NAME                   "fonts/Helvetica_Rounded_LT_Bold_Condensed.ttf"
#define PRODUCT_ID                          "com.tdgc.videopokerjackpot"
#endif

// Define User Default settings
#define USER_DEFAULT_SOUND_EFFECT           "SETTINGS_SOUND_EFFECT"
#define USER_DEFAULT_MUSIC                  "SETTINGS_MUSIC"
#define USER_DEFAULT_LEFT_HAND              "SETTINGS_LEFT_HAND"
#define USER_DEFAULT_DOUBLE_OR_NOTHING      "SETTINGS_DOUBLE_OR_NOTHING"

#define TOTAL_AVATAR_NUMBER                 9


#define NEW_MENU_ITEM_SPRITE(menuItemName, normalImage, selectedImage, callbackFunction) { \
    CCSprite* normalSprite = CCSprite::create(normalImage); \
    CCSprite* selectedSprite = CCSprite::create(selectedImage); \
    menuItemName = CCMenuItemSprite::create(normalSprite, \
                                                selectedSprite, \
                                                this, \
                                                menu_selector(callbackFunction)); \
}

#define CREATE_MENUITEM_SPRITE(menuItemName, normalImage, selectedImage, callbackFunction) \
protected: \
    CCMenuItem* m##menuItemName; \
private: \
    void add##menuItemName(CCMenu* parent, const CCPoint &pPosition) { \
        CCSprite* normalSprite = CCSprite::create(normalImage); \
        CCSprite* selectedSprite = CCSprite::create(selectedImage); \
        m##menuItemName = CCMenuItemSprite::create(normalSprite, \
            selectedSprite, \
            this, \
            menu_selector(callbackFunction)); \
        m##menuItemName->setPosition(pPosition); \
        parent->addChild(m##menuItemName); \
    }

#define MAP_ITERATOR(_mapName, it) for(auto it = _mapName.begin() ; it != _mapName.end(); it++)

#define SAFE_DELETE_VECTOR_POINTER(pVector) \
for(int i = 0 ; i < pVector->size() ; i++) { \
    if(pVector->at(i)) { \
        delete pVector->at(i); \
    } \
} \
pVector->clear(); \
delete pVector;


// define avatar downloader callback
typedef void (CCObject::*AvatarLoadedCallback)(CCSprite*, CCObject*);
#define avatar_selector(_SELECTOR) (AvatarLoadedCallback)(&_SELECTOR)

////////////////////////////////////////////////////////////////////////////////////////////////////
// Number with commas formatted
////////////////////////////////////////////////////////////////////////////////////////////////////

class comma_numpunct : public std::numpunct<char>
{
protected:
    virtual char do_thousands_sep() const
    {
        return ',';
    }
    
    virtual std::string do_grouping() const
    {
        return "\03";
    }
};

template<class T>
std::string FormatWithCommas(T value)
{
    std::locale comma_locale(std::locale(), new comma_numpunct());
    std::stringstream ss;
    ss.imbue(comma_locale);
    ss << std::fixed << value;
    return ss.str();
}

/// macro to get TextFromCurrencyNumber
#define CURRENCY_LONG(k) (FormatWithCommas(k).c_str())

////////////////////////////////////////////////////////////////////////////////////////////////////
// GameParams Class
////////////////////////////////////////////////////////////////////////////////////////////////////

class GameParams : public SingLeton<GameParams>
{
public:
	GameParams();
    void initParams();
    
    bool isSoundOn;
    bool isMusicOn;
    bool isDonEnabled;
    bool isLeftHand;
    bool isIpadDevice;
    
    void getUserDefaultSettings();
    
    void initIpadParams();
    void initIphone4Params();
    void initIphone5Params();
    void initIphone4_5Params();
    
    
    // font size
    float CMM_FONT_SIZE_0;
    float CMM_FONT_SIZE_1;
    float CMM_FONT_SIZE_2;
    float CMM_FONT_SIZE_3;
    float CMM_FONT_SIZE_4;
    float CMM_FONT_SIZE_5;
    float CMM_FONT_SIZE_6;
    float CMM_CARD_FONT_SIZE;
    
    CCSize CMM_ICON_FB_SIZE;
    CCSize CMM_ICON_LOBBY_SIZE;
    CCSize CMM_ICON_PROFILE_SIZE;
    CCSize CMM_ICON_AVATAR_SIZE;

    //
    // Login scene
    //
    CCPoint LOG_STATUS_LABEL_POSITION;
    CCPoint LOG_PROGRESS_BAR_POSITION;
    CCPoint LOG_BONUS_FB_LOGIN_POSITION;
    CCPoint LOG_FB_BUTTON_POSITION;
    CCPoint LOG_GUEST_BUTTON_POSITION;

    // parameters for select game layer
    CCPoint LBB_SELECT_GAME_HEADER_POSITION;
    CCPoint LBB_PAGE_INDICATOR_ON_SELECT_GAME_POSITION;

    CCPoint LBB_STACKS_IN_MENU_ITEM_POSITION;
    CCPoint LBB_JACKPOT_LABEL_IN_MENU_ITEM_POSITION;
    CCPoint LBB_JACKPOT_SPRITE_IN_MENU_ITEM_POSITION;
    CCPoint LBB_LOCK_SPRITE_IN_MENU_ITEM_POSITION;
    CCPoint LBB_LOCK_LABEL_IN_MENU_ITEM_POSITION;
    
    CCRect  LBB_SELECT_GAME_SCROLL_VIEW_BOUNDING_BOX;
    int     LBB_NUMBER_OF_MENU_ITEM_ON_SELECT_GAME;
    
    CCPoint LBB_GAME_LIST_POSITION[4];

    CCPoint LBB_HEADER_BG_POSITION;
    CCPoint LBB_HEADER_SETTINGS_BUTTON_POSITION;
    
    CCPoint LBB_MIDDLE_BG_POSITION;
    CCPoint LBB_MIDDLE_CHIP_BG_POSITION;
    CCPoint LBB_MIDDLE_CHIP_ICON_POSITION;
    CCPoint LBB_MIDDLE_CHIP_LABEL_POSITION;
    CCPoint LBB_MIDDLE_CHIP_BUTTON_POSITION;
    CCPoint LBB_MIDDLE_BONUS_BG_POSITION;
    CCPoint LBB_MIDDLE_BONUS_LABEL_POSITION;
    CCPoint LBB_MIDDLE_BONUS_BUTTON_POSITION;

    CCPoint LBB_FOOTER_BG_POSITION;
    CCPoint LBB_FOOTER_AVATAR_POSITION;
    CCPoint LBB_FOOTER_LEVEL_BAR_POSITION;
    CCPoint LBB_FOOTER_LEVEL_LABEL_POSITION;
    CCPoint LBB_FOOTER_FULLNAME_POSITION;
    

    //Main game UI define
    CCPoint MAIN_GAME_INFO_LAYOUT_POSITION;
    CCPoint MAIN_BET_CHIP_BUTTONS_LAYOUT_POSITION;
    CCPoint MAIN_EXPECTED_AND_DEALING_LAYOUT_POSITION;
    CCPoint MAIN_LV_LAYOUT_POSITION;
    CCPoint MAIN_TOTAL_CHIP_LAYOUT_POSITION;
    CCPoint MAIN_BET_CHIP_LAYOUT_POSITION;
    
    //Main game UI button define
    CCPoint MAIN_EXIT_BUTTON_POSITION;
    CCPoint MAIN_SETTINGS_BUTTON_POSITION;
    CCPoint MAIN_ADD_CHIP_BUTTON_POSITION;
    CCPoint MAIN_DEAL_BUTTON_POSITION;
    CCPoint MAIN_MAX_BET_BUTTON_POSITION;
    CCPoint MAIN_BET_CHIP_BUTTONS_POSITIONS[3];
    CCPoint MAIN_TOTAL_BET_CHIP_BUTTON_POSITION;
    CCPoint MAIN_DON_YES_BUTTON_POSITION;
    CCPoint MAIN_DON_NO_BUTTON_POSITION;
    float MAIN_DON_MOVING_DISTANCE;

    //Main game UI label define
    CCPoint MAIN_TOTAL_CHIPS_LABEL_POSITION;
    CCPoint MAIN_BET_CHIPS_LABEL_POSITION;
    CCPoint MAIN_WON_CHIPS_LABEL_POSITION;
    CCPoint MAIN_JACKPOT_VALUE_LABEL_POSITION;
    CCPoint MAIN_BET_CHIPS_SPRITE_POSITION;
    CCPoint MAIN_WON_CHIPS_SPRITE_POSITION;

    CCPoint MAIN_HAND_OF_JACKPOT_LABEL_POSTION;
    CCPoint MAIN_JACKPOT_STRING_LABEL_POSITION;
    CCPoint MAIN_TOTAL_USER_LABEL_POSITION;
    CCPoint MAIN_DON_LABEL_POSITION;
    
    // Main game bg
    CCPoint MAIN_HEADER_BG_POSITION;
    CCPoint MAIN_HEADER_LEVEL_POSITION;
    CCPoint MAIN_HEADER_BOARD_POSITION;
    CCPoint MAIN_PAYTABLE_BG_POSITION;
    CCPoint MAIN_CHIP_INFO_BG_POSITION;
    CCPoint MAIN_TOTAL_CHIP_BG_POSITION;
    CCPoint MAIN_TOTAL_CHIP_ICON_POSITION;
    CCPoint MAIN_BET_CHIP_BG_POSITION;
    CCPoint MAIN_FUNCTION_BG_POSITION;
    CCPoint MAIN_FUNCTION_BUTTON_BG_POSITION;

    // Paytable cell
    float   MAIN_PAYTABLE_CELL_NAME_DELTA;
    CCPoint MAIN_PAYTABLE_CELL_POSITIONS[10];

    CCPoint MAIN_BETTING_CREDIT_AREA_PgitOSITION;
    CCPoint MAIN_LEVEL_LABEL_POSITION;
        
    //cards
    CCPoint MAIN_CARDS_POSITIONS[5];
    CCPoint MAIN_HELDINGS_POSITIONS[5];

    //Cards
    CCPoint CARD_RANK_LABEL_POSITION;
    CCPoint CARD_SUIT_SMALL_ICON_POSITION;
    CCPoint CARD_SUIT_ICON_POSITION;
    CCPoint CARD_JQK_ICON_POSITION;
    CCPoint CARD_JQK_SUIT_ICON_POSITION;
    CCPoint CARD_WILD_ICON_POSITION;
    CCPoint CARD_JOKER_ICON_POSITION;
    CCPoint CARD_JOKER_LABEL_POSITION;
    
    // popup
    CCPoint POP_COMMON_EXIT_BUTTON_POSITION;
    CCPoint POP_COMMON_HEADER_POSITION;
    
    // Notification popup
    CCPoint NTF_TITLE_TEXT_POSITION;
    CCPoint NTF_MESSAGE_TEXT_POSITION;
    CCPoint NTF_BUTTON_CENTER_POSITION;
    CCPoint NTF_BUTTON_LEFT_POSITION;
    CCPoint NTF_BUTTON_RIGHT_POSITION;
    CCSize  NTF_MESSAGE_SIZE;
    
    //pay table popup
    CCPoint POP_PAYTABLE_HAND_MENUITEMS_POSITIONS[12];
    CCPoint POP_PAYTABLE_CARDS_POSTIONS[5];
    CCPoint POP_PAYTABLE_CARD_VIEW_CONTAINER_POSITION;
    
    CCPoint POP_PAYTABLE_PAYOUT_SPRITE_POSITION;
    CCPoint POP_PAYTABLE_PAYOUT_LABEL_POSITION;
    
    //setting popup
    CCPoint POP_SETTING_HEADER_POSITION;
    
    CCPoint POP_SETTING_SOUND_EFFECT_LABEL_POSITION;
    CCPoint POP_SETTING_MUSIC_LABEL_POSITION;
    CCPoint POP_SETTING_LEFT_HAND_LABEL_POSITION;
    CCPoint POP_SETTING_DOUBLE_OR_NOTHING_LABEL_POSITION;
    
    CCPoint POP_SETTING_SOUND_EFFECT_MENUITEM_POSITION;
    CCPoint POP_SETTING_MUSIC_MENUITEM_POSITION;
    CCPoint POP_SETTING_LEFT_HAND_MENUITEM_POSITION;
    CCPoint POP_SETTING_DOUBLE_OR_NOTHING_MENUITEM_POSITION;
    
    CCPoint POP_SETTING_RATE_US_MENUITEM_POSITION;
    CCPoint POP_SETTING_FEEDBACK_MENUITEM_POSITION;
    CCPoint POP_SETTING_LIKE_PAGE_MENUITEM_POSITION;
    CCPoint POP_SETTING_INVITE_FRIEND_MENUITEM_POSITION;
    CCPoint POP_SETTING_PRIVATE_POLICY_MENUITEM_POSITION;
    CCPoint POP_SETTING_TERM_OF_SERVICES_MENUITEM_POSITION;
    
    //shopping popup
    CCPoint POP_SHOP_PACKET_NAME_LABEL_POSITION;
    CCPoint POP_SHOP_CHIP_AMOUNT_LABEL_POSITION;
    CCPoint POP_SHOP_VIP_POINT_LABEL_POSITION;
    CCPoint POP_SHOP_PRICE_MENUITEM_POSITION;
    CCPoint POP_SHOP_MAIN_ICON_SPRITE_POSITION;
    CCPoint POP_SHOP_CHIP_ICON_SPRITE_POSITION;
    CCPoint POP_SHOP_STAR_ICON_SPRITE_POSITION;
    CCPoint POP_SHOP_TABLEVIEW_POSITION;
    CCPoint POP_SHOP_PRODUCT_MENUITEMS_POSITIONS[2];
    CCSize  POP_SHOP_TABLEVIEW_CELL_SIZE;
    CCSize  POP_SHOP_TABLEVIEW_SIZE;
    CCRect  POP_SHOP_MENU_BOUNDINGBOX;
    
    //profile popup
    CCPoint POP_PROFILE_AVARTAR_MENUITEM_POSITION;
    CCPoint POP_PROFILE_VIP_CLUB_MENUITEM_POSITION;
    CCPoint POP_PROFILE_LOGOUT_MENUITEM_POSITION;
    
    CCPoint POP_PROFILE_CIRCLE_AVATAR_SPRITE_POSITION;
    CCPoint POP_PROFILE_BEST_HAND_SPRITE_POSITION;
    CCPoint POP_PROFILE_WIN_RATIO_SPRITE_POSITION;
    CCPoint POP_PROFILE_BIGGEST_WIN_SPRITE_POSITION;
    CCPoint POP_PROFILE_HANDS_WON_SPRITE_POSITION;
    CCPoint POP_PROFILE_HANDS_PLAYED_SPRITE_POSITION;
    CCPoint POP_PROFILE_LEVEL_ICON_SPRITE_POSITION;
    CCPoint POP_PROFILE_LOCATION_ICON_SPRITE_POSITION;
    CCPoint POP_PROFILE_CHIP_ICON_SPRITE_POSITION;
    CCPoint POP_PROFILE_GENDER_ICON_SPRITE_POSITION;
    
    CCPoint POP_PROFILE_BEST_HAND_LABEL_POSITION;
    CCPoint POP_PROFILE_WIN_RATIO_LABEL_POSITION;
    CCPoint POP_PROFILE_BIGGEST_WIN_LABEL_POSITION;
    CCPoint POP_PROFILE_HANDS_WON_LABEL_POSITION;
    CCPoint POP_PROFILE_HANDS_PLAYED_LABEL_POSITION;
    
    CCPoint POP_PROFILE_NICKNAME_LABEL_POSITION;
    CCPoint POP_PROFILE_CHIPS_LABEL_POSITION;
    CCPoint POP_PROFILE_LOCATION_LABEL_POSITION;
    CCPoint POP_PROFILE_LEVEL_LABEL_POSITION;
    
    CCPoint POP_PROFILE_CARDS_POSTIONS[5];
    
    //dailybonus popup
    CCPoint POP_DAILYBONUS_LEVEL_SEPARATE_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_LEVEL_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_VIP_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_FACEBOOK_SEPARATE_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_DAYS_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_FACEBOOK_FRIEND_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_CLAIM_MENUITEM_POSITION;
    CCPoint POP_DAILYBONUS_TOTAL_BONUS_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_HEADER_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_SLIVER_CARD_SPRITE_POSITION;
    CCPoint POP_DAILYBONUS_COMEBACK_SPRITE_POSITION;
    
    CCPoint POP_DAILYBONUS_DAYS_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_DAYS_CHIPS_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_FACEBOOK_FRIEND_PART_ONE_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_FACEBOOK_FRIEND_PART_TWO_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_FACEBOOK_FRIEND_CHIPS_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_LEVEL_PART_ONE_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_LEVEL_PART_TWO_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_LEVEL_CHIPS_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_VIP_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_VIP_CHIPS_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_TOTAL_BONUS_TEXT_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_TOTAL_BONUS_VALUE_LABEL_POSITION;
    CCPoint POP_DAILYBONUS_DAYS_VALUE_LABEL_POSITION;
    
    CCSize POP_DAILYBONUS_DAYS_LABEL_DIMENSION;
    CCSize POP_DAILYBONUS_VIP_LABEL_DIMENSION;
    
    //vip club popup
    CCPoint POP_VIPCLUB_PLATINUM_TEXT_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_PLATINUM_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_MEMBER_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_LINES_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_TEXT_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_HEADER_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BIG_PLATINUM_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_TEXT_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_TEXT_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BIG_BRONZE_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_PROGRESS_LEVEL_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_PROGRESS_LEVEL_BACKGROUND_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BIG_GOLD_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BIG_SLIVER_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_GOLD_TEXT_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_BIG_DIAMOND_CARD_SPRITE_POSITION;
    CCPoint POP_VIPCLUB_GOLD_CARD_SPRITE_POSITION;
    
    CCPoint POP_VIPCLUB_CHECKED_SPRITES_POSITIONS[5];
    
    CCPoint POP_VIPCLUB_NOTE_MORE_POINTS_LABEL_POSITION;
    CCPoint POP_VIPCLUB_NOTE_MULTIPLE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_VIP_POINT_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_VIP_POINT_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_PACKAGES_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_BRONZE_PACKAGES_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_VIP_POINT_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_VIP_POINT_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_PACKAGES_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_SLIVER_PACKAGES_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_GOLD_VIP_POINT_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_GOLD_VIP_POINT_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_GOLD_PACKAGES_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_GOLD_PACKAGES_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_PLATINUM_VIP_POINT_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_PLATINUM_VIP_POINT_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_PLATINUM_PACKAGES_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_PLATINUM_PACKAGES_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_VIP_POINT_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_VIP_POINT_VALUE_LABEL_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_PACKAGES_TEXT_LABEL_POSITION;
    CCPoint POP_VIPCLUB_DIAMOND_PACKAGES_VALUE_LABEL_POSITION;
    
    /**
     *  AvatarsPopupView position declare
     * by apple
     */
	CCPoint POP_AVATARS_AVATARS_SPRITE_POSITIONS[TOTAL_AVATAR_NUMBER];
	CCPoint POP_AVATARS_AVATAR_1_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_2_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_3_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_4_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_5_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_6_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_7_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_8_SPRITE_POSITION;
	CCPoint POP_AVATARS_AVATAR_9_SPRITE_POSITION;
	CCPoint POP_AVATARS_FB_ICON_SPRITE_POSITION;
	CCPoint POP_AVATARS_CONTAINER_TABLE_POSITION;
	CCPoint POP_AVATARS_CURRENT_BACKGROUND_SPRITE_POSITION;
	CCPoint POP_AVATARS_INFRAME_SPRITE_POSITION;
	CCPoint POP_AVATARS_USE_ACTIVE_SPRITE_POSITION;
	CCPoint POP_AVATARS_USE_BACKGROUND_SPRITE_POSITION;
	CCPoint POP_AVATARS_USE_MENUITEM_POSITION;
	CCPoint POP_AVATARS_USE_MENU_POSITION;
    CCPoint POP_AVATARS_CELL_POSITION;
    
    CCSize POP_AVATARS_CONTAINER_TABLE_SIZE;
    CCSize POP_AVATARS_CONTAINER_TABLE_CELL_SIZE;
    
    //
    // Loading scene
    //
    CCPoint LOADING_PROGRESS_BAR_POSITION;
    
    
	/**
     * JackpotPopupView position declare
     * by apple
     */
	CCPoint POP_JACKPOT_CHIPS_SPRITE_POSITION;
	CCPoint POP_JACKPOT_JACKPOT_TEXT_SPRITE_POSITION;
	CCPoint POP_JACKPOT_REWARD_ICON_SPRITE_POSITION;
	CCPoint POP_JACKPOT_SHINE_CIRCLE_SPRITE_POSITION;
	CCPoint POP_JACKPOT_STAR_SHINE_SPRITE_POSITION;
    CCPoint POP_JACKPOT_OK_MENUITEM_POSITION;
    CCPoint POP_JACKPOT_SHARE_MENUITEM_POSITION;
    CCPoint POP_JACKPOT_CHIPS_LABEL_POSITION;
    CCPoint POP_JACKPOT_STARS_POSITIONS[4];

	

	/**
	* VipUpgradePopupView  position declare
	* by apple
	*/
	CCPoint POP_VIP_UPGRADE_CHIPS_LABEL_POSITION;
	CCPoint POP_VIP_UPGRADE_INAPP_LABEL_POSITION;
	CCPoint POP_VIP_UPGRADE_MEMBER_CARD_SPRITE_POSITION;
	CCPoint POP_VIP_UPGRADE_OK_MENUITEM_POSITION;
	CCPoint POP_VIP_UPGRADE_REWARD_ICON_SPRITE_POSITION;
	CCPoint POP_VIP_UPGRADE_SHARE_MENUITEM_POSITION;
	CCPoint POP_VIP_UPGRADE_SHINE_SPRITE_POSITION;
	CCPoint POP_VIP_UPGRADE_STAR1_SPRITE_POSITION;
	CCPoint POP_VIP_UPGRADE_STAR2_SPRITE_POSITION;
	CCPoint POP_VIP_UPGRADE_VIP_LEVEL_RIBBON_SPRITE_POSITION;

	

	/**
	* LevelupPopupView  position declare
	* by apple
	*/
	CCPoint POP_LEVELUP_CIRCLE_CONTAINER_1_SPRITE_POSITION;
	CCPoint POP_LEVELUP_CIRCLE_CONTAINER_2_SPRITE_POSITION;
	CCPoint POP_LEVELUP_CONGRATULATION_LABEL_POSITION;
	CCPoint POP_LEVELUP_LEVEL_LABEL_POSITION;
	CCPoint POP_LEVELUP_OK_MENUITEM_POSITION;
	CCPoint POP_LEVELUP_RIBBON_SPRITE_POSITION;
	CCPoint POP_LEVELUP_SHARE_MENUITEM_POSITION;
	CCPoint POP_LEVELUP_SHINE_CIRCLE_SPRITE_POSITION;
	CCPoint POP_LEVELUP_STAR1_SPRITE_POSITION;
	CCPoint POP_LEVELUP_STAR2_SPRITE_POSITION;
	CCPoint POP_LEVELUP_STAR3_SPRITE_POSITION;
	CCPoint POP_LEVELUP_STAR_SHINE_SPRITE_POSITION;
    
    float   POP_PROFILE_CARD_SCALE;

	//don't modify or delete this line

private:
    CCPoint MakePoint(float x, float y);
    CCPoint MakePointCommon(float x, float y);
};

#define GPARAMS() GameParams::getSingleton()

#endif /* defined(__Dragon_Poker__GameParams__) */
