/**
* This file is auto generated by Twin Dragons Tools
* LevelupPopupView.h
* DragonVideoPoker
*
* Created by apple on Sat Jun 07 11:07:29 GMT+07:00 2014
*
**/

#ifndef __DragonVideoPoker__LevelupPopupView__
#define __DragonVideoPoker__LevelupPopupView__

#include "cocos-ext.h"

#include "PopUpLayer.h"
#include "Defines.h"

using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class LevelupPopupView : public PopUpLayer {

public:
	static LevelupPopupView* create(const string &pLevel,
                                    string pBackgroundImage = D::id.levelup_popup_background_level,
                                   string pExitNormalImage = "",
                                   string pExitSelectedImage = "");
    
    virtual bool init(const string &pLevel,
                      string pBackgroundImage = D::id.levelup_popup_background_level,
                      string pExitNormalImage = "",
                      string pExitSelectedImage = "");
    
 protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    virtual void onActionShowFinished();

private:
	enum MenuItemTag {
		
		okMenuItemTag	= 1000,
		shareMenuItemTag	= 1001,

	};
	
	void levelupMenuItemCallback(CCObject *pSender);
	
	//{extend_functions}

	
	CCSprite* mOkActiveSprite;
	
	CCSprite* mOkNormalSprite;

	CCMenuItem* mOkMenuItem;
	
	CCSprite* mShareActiveSprite;
	
	CCSprite* mShareNormalSprite;

	CCMenuItem* mShareMenuItem;

	CCSprite* mCircleContainer1Sprite;
	
	CCSprite* mCircleContainer2Sprite;
	
	CCSprite* mRibbonSprite;
	
	CCSprite* mShineCircleSprite;
	
	CCSprite* mStar1Sprite;
	
	CCSprite* mStar2Sprite;
	
	CCSprite* mStar3Sprite;
	
	CCSprite* mStarShineSprite;

	CCLabelTTF* mCongratulationLabel;
	
	CCLabelTTF* mLevelLabel;
    
    string mLevelString;


};

#endif /* defined(__DragonVideoPoker__LevelupPopupView__) */
