/**
* This file is auto generated by Twin Dragons Tools
* LobbyLayerView.h
* TomCuaCaOnline
*
* Created by apple on Thu Sep 25 14:11:51 GMT+07:00 2014
*
**/

#ifndef __TomCuaCaOnline__LobbyLayerView__
#define __TomCuaCaOnline__LobbyLayerView__

#include "cocos-ext.h"

#include "CommonLayer.h"
#include "TableLayer.h"

using namespace std;
using namespace cocos2d;

class ITableCellView;
class TableView;
class LobbyLayerView : public TableLayer {
public:
	static Scene* createScene();
	static LobbyLayerView* create(//{parameters}
								);
    
    virtual bool init(//{parameters}
    				);	
                    
   	virtual ITableCellView* createTableViewCellAt(const int &idx);
 
 protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenus();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    virtual void addTables();
    
private:
	enum MenuItemTag {
		
		playNowmenuitemTag = 1,

		rankingmenuitemTag = 5,
		shoppingmenuitemTag = 6,
		vipClubmenuitemTag = 7,

	};
	
	void lobbyMenuItemCallback(Ref *pSender);

    extension::TableView* mRoomListTable;

};
#endif /* defined(__TomCuaCaOnline__LobbyLayerView__) */
