/**
* This file is auto generated by Twin Dragons Tools
* LobbyLayerView.cpp
* TomCuaCaOnline
*
* Created by apple on Thu Sep 25 14:11:51 GMT+07:00 2014
*
**/
#include "LobbyLayerView.h"
#include "CommonLayer.h"
#include "ITableCellView.h"
#include "TableView.h"
#include "LobbyLayerCellView.h"



Scene* LobbyLayerView::createScene() {
    LobbyLayerView* layer = LobbyLayerView::create(//{importing_params}
    				);
    Scene* pRet = Scene::create();
    pRet->addChild(layer);
    
    return pRet;
}

LobbyLayerView* LobbyLayerView::create(//{parameters}
								) {
    LobbyLayerView* pRet = new LobbyLayerView();
    pRet->autorelease();
    pRet->init(//{importing_params}
    		);
    
    return pRet;
}

bool LobbyLayerView::init() {             
	
    CommonLayer::init();
    this->setColor(Color3B(0, 0, 255));
    //setBackgroundPosition(VisibleRect::center());

    
    return true;
}

void LobbyLayerView::addMenus() {
	CommonLayer::addMenus();
    
}

void LobbyLayerView::addMenuItems() {
    CommonLayer::addMenuItems();
}

void LobbyLayerView::addSprites() {
	CommonLayer::addSprites();
}

void LobbyLayerView::addLabels() {
	CommonLayer::addLabels();	
   
}

void LobbyLayerView::addProgressBars() {
	CommonLayer::addProgressBars();
	
}

void LobbyLayerView::addTables() {
	CommonLayer::addTables();
	
		//create group of tables
    mRoomListTable = gameview::ext::TableView::create(
                                       Size(200, 100),
                                       1,
                                       1,
                                       Vec2(100, 50),
                                       Size(200, 200),
                                       this,
                                       NULL);
	mRoomListTable->setPosition(Vec2(50, 10));
	mRoomListTable->setDelegate(this);
	this->addChild(mRoomListTable);

}

void LobbyLayerView::addActions() {
    CommonLayer::addActions();
    
    //{add_actions}
}

ITableCellView* LobbyLayerView::createTableViewCellAt(const int &idx) {
    ITableCellView *pRet = LobbyLayerCellView::create(idx);
    
    return pRet;
}

void LobbyLayerView::lobbyMenuItemCallback(Ref *pSender) {
    
    MenuItem* menuItem = static_cast<MenuItem*>(pSender);
        
    switch (menuItem->getTag()) {
        //{menuitem_cases}
    }
}
