/**
* This file is auto generated by Twin Dragons Tools
* LeaderboardPopupView.h
* DragonVideoPoker
*
* Created by apple on Mon Jul 28 10:51:18 GMT+07:00 2014
*
**/

#ifndef __DragonVideoPoker__LeaderboardPopupView__
#define __DragonVideoPoker__LeaderboardPopupView__

#include <vector>

#include "cocos-ext.h"

#include "PopUpLayer.h"
#include "Defines.h"
#include "WaitingLayer.h"
#include "ITableViewBuilder.h"

using namespace std;
using namespace cocos2d;
using namespace cocos2d::extension;

class ITableCellView;
class TableView;

class LeaderboardPopupView : public PopUpLayer, public ITableViewBuilder {

public:
    ~LeaderboardPopupView();
	static LeaderboardPopupView* create(
							string pBackgroundImage = D::id.common_background,
                            string pExitNormalImage = D::id.popup_common_exit_normal,
                            string pExitSelectedImage = D::id.popup_common_exit_active);
    
    virtual bool init(
    				string pBackgroundImage = D::id.common_background,
                    string pExitNormalImage = D::id.popup_common_exit_normal,
                    string pExitSelectedImage = D::id.popup_common_exit_active);
    virtual void update(float dt);
    
    virtual ITableCellView* createTableViewCellAt(const int &idx);
 
 protected:
    virtual void addSprites();
    virtual void addLabels();
    virtual void addMenuItems();
    virtual void addProgressBars();
    virtual void addActions();
    virtual void addTables();
    virtual void onActionShowFinished();

    virtual void onExit();

private:
	enum MenuItemTag {
		
	};
	
    void addWaitingLayerWithType(int type);
	void removeWaitingLayer(int type);
    void onGetDataFinished(CCObject* object);
    void updateView();
	
	CCSprite* mLeaderboardBannerSprite;

	CCLabelTTF* mYourPositionLabel;
    
    TableView* mTableView;
    WaitingLayer* mWaitingLayer;
    
    vector<CCLabelTTF*> mFullNameLabels;
    vector<CCLabelTTF*> mChipsLabels;
    vector<CCSprite*> mNumberSprites;
    
    bool mIsUpdate;

};

#endif /* defined(__DragonVideoPoker__LeaderboardPopupView__) */
